# Generated by Django 3.2.6 on 2021-08-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOTHER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=100)),
                ('L_Name', models.CharField(max_length=100)),
                ('Reg_No', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CHILD1',
            fields=[
                ('mother_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ACCOUNTS2.mother')),
                ('Age', models.IntegerField()),
            ],
            bases=('ACCOUNTS2.mother',),
        ),
    ]
