# Generated by Django 3.2.6 on 2021-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='Select',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, null=True),
        ),
    ]
